### PR TITLE
Add Visual C++ 2005 runtimes

### PR DESCRIPTION
**Pull request by taliesins**
Some old applications still make use of 2005 C++ Runtime, so I added support for it.

### CODE REVIEW

**Comment by axelrtgs** [comment]
i would love to see this included in master as well, i will use this to also add latest 2015 run times since we need the full suite.

**Comment by taliesins** [comment]
@tas50 is this a dead repo?

**Comment by tas50** [comment]
I don't have access to this repo, but it would be really great to get it migrated somewhere where it can be maintained.

**Comment by axelrtgs** [comment]
these changes and more are included in https://github.com/chef-windows/vcruntime/pull/8 this can be closed/deleted once https://github.com/chef-windows/vcruntime/pull/8 gets merged since it includes the changes from this request.

**Comment by tas50** [comment]
#8 has been merged into master which includes this fix

**Pull request closed without merging**
